#!/bin/bash 
#
# profilemonitor -  bash script to monitor profile synchronisation
#
# Copyright (C) 2016 bitpack.io <hello@bitpack.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

config="/usr/local/bin/profile.conf"
library="/usr/local/bin/profilelib"

[ -f ${config} ] && {
  source ${config} 
} || {
  exit -1;
}

[ -f ${library} ] && {
  source ${library} 
} || {
  exit -2;
}

configure 
lock "/tmp/profilemonitor.lock-${USER}"

cleanup() {
  log "info: caught signal to exiting profilemonitor for user ${USER}" 
  kill -TERM "$child" 2>/dev/null && {
    log "info: profilesync for user ${USER} terminated successfully";
  } || {
    log "info: error while terminating profilesync for user ${USER}";
  }
}

trap cleanup SIGHUP SIGINT SIGQUIT SIGTERM

log "info: executing synchronisation for ${USER}...";
${bin_profilesync} &
child=$! 
log "info: waiting for synchronisation for ${USER} under pid ${child} ...";
wait "$child" 
ret=$?

[ "${ret}" -eq "0" ] || [ "${ret}" -eq "143" ] && {
  log "info: profilesync returned expected with status ${ret}"
  sync_to_fileserver
} || {
  log "info: profilesync returned unexpected with status ${ret}"
  log "info: profile for ${USER} not synchronized to fileserver";
}

unlock "/tmp/profilesync.lock-${USER}"
unlock "/tmp/profilemonitor.lock-${USER}"

